name: "Terraform Validation"
on:
  - push

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 0.15.4
      - name: Init
        run: terraform init -backend=false
      - name: Lint
        run: terraform validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_name: "name"
          TF_VAR_hosted_zone: "hosted_zone"
          TF_VAR_domain_name: "domain_name"
          AWS_DEFAULT_REGION: "us-west-1"
